#!/bin/bash
CPPNames='usort addtargets2 alignchime alignchimel alnparams alpha alpha2 fractid getparents globalalign2 make3way mx myutils path searchchime seqdb setnucmx sfasta tracebackbit uchime_main viterbifast writechhit'
ObjNames='usort.o addtargets2.o alignchime.o alignchimel.o alnparams.o alpha.o alpha2.o fractid.o getparents.o globalalign2.o make3way.o mx.o myutils.o path.o searchchime.o seqdb.o setnucmx.o sfasta.o tracebackbit.o uchime_main.o viterbifast.o writechhit.o'

rm -f *.o uchime.make.stdout.txt uchime.make.stderr.txt

for CPPName in $CPPNames
do
  echo $CPPName >> /dev/tty
  g++ $ENV_GCC_OPTS -DUCHIMES=1 -c -O3 -msse2 -mfpmath=sse -D_FILE_OFFSET_BITS=64 -DNDEBUG=1 $CPPName.cpp -o $CPPName.o  >> uchime.make.stdout.txt 2>> uchime.make.stderr.txt
done

LINK_OPTS=
if [ `uname -s` == Linux ] ; then
    LINK_OPTS=-static
fi
g++ $LINK_OPTS $ENV_LINK_OPTS -g -o uchime $ObjNames  >> uchime.make.stdout.txt 2>> uchime.make.stderr.txt
tail uchime.make.stderr.txt

strip uchime
ls -lh uchime
sum uchime
