#!/bin/sh

##
# hg18_jar
#
#  Authors: Ben Langmead & Michael C. Schatz
#     Date: 10/9/2009
#
# Driver script for building a reference jar for the hg18 human genome
# assembly.

HG18_BASE=ftp://hgdownload.cse.ucsc.edu/goldenPath/hg18/chromosomes

mkdir -p .hg18
mkdir -p .hg18/sequences

BUILD_INPUTS=

j=0
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y ; do
	wget $HG18_BASE/chr$i.fa.gz -O .hg18/sequences/zchr$j.fa.gz
	gunzip .hg18/sequences/zchr$j.fa.gz
	sed -e "s/^>.*/>$j/" .hg18/sequences/zchr$j.fa > .hg18/sequences/chr$j.fa
	rm -f .hg18/sequences/zchr$j.fa
	[ ! -f .hg18/sequences/chr$j.fa ] && echo "Didn't get .hg18/sequences/chr$j.fa" && exit 1
	if [ -z "$BUILD_INPUTS" ] ; then
		BUILD_INPUTS=".hg18/sequences/chr$j.fa"
	else
		BUILD_INPUTS="$BUILD_INPUTS,.hg18/sequences/chr$j.fa"
	fi
	j=`expr $j + 1`
done

mkdir -p .hg18/index
bowtie-build $BUILD_INPUTS .hg18/index/index

sh db2ssnp_hg18
mv hg18snps .hg18/snps
mv .hg18 hg18
echo "Output in hg18"
pushd hg18
mv snps/cmap.txt .
touch cmap.txt
echo "Running jar cf hg18.jar sequences snps index cmap.txt"
jar cf hg18.jar sequences snps index cmap.txt
popd
