#!/bin/sh

##
# mm9_jar
#
#  Authors: Ben Langmead & Michael C. Schatz
#     Date: 10/9/2009
#
# Driver script for building a reference jar for the mm9 human genome
# assembly.

MM9_BASE=ftp://hgdownload.cse.ucsc.edu/goldenPath/mm9/chromosomes

mkdir -p .mm9
mkdir -p .mm9/sequences

BUILD_INPUTS=

j=0
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 X Y ; do
	wget $MM9_BASE/chr$i.fa.gz -O .mm9/sequences/zchr$j.fa.gz
	gunzip .mm9/sequences/zchr$j.fa.gz
	sed -e "s/^>.*/>$j/" .mm9/sequences/zchr$j.fa > .mm9/sequences/chr$j.fa
	rm -f .mm9/sequences/zchr$j.fa
	[ ! -f .mm9/sequences/chr$j.fa ] && echo "Didn't get .mm9/sequences/chr$j.fa" && exit 1
	if [ -z "$BUILD_INPUTS" ] ; then
		BUILD_INPUTS=".mm9/sequences/chr$j.fa"
	else
		BUILD_INPUTS="$BUILD_INPUTS,.mm9/sequences/chr$j.fa"
	fi
	j=`expr $j + 1`
done

mkdir -p .mm9/index
bowtie-build $BUILD_INPUTS .mm9/index/index

sh db2ssnp_mm9
mv mm9snps .mm9/snps
mv .mm9 mm9
echo "Output in mm9"
pushd mm9
mv snps/cmap.txt .
touch cmap.txt
echo "Running jar cf mm9.jar sequences snps index cmap.txt"
jar cf mm9.jar sequences snps index cmap.txt
popd
