#!/bin/sh

##
# db2ssnp_hg18
#
#  Authors: Ben Langmead & Michael C. Schatz
#     Date: 10/9/2009
#
# Invoke db2ssnp with appropriate arguments for each human chromosome.

NAME=hg18

mkdir -p .${NAME}snps
cat <<EOF > .${NAME}snps/snp_cmap.txt
1	0
2	1
3	2
4	3
5	4
6	5
7	6
8	7
9	8
10	9
11	10
12	11
13	12
14	13
15	14
16	15
17	16
18	17
19	18
20	19
21	20
22	21
X	22
Y	23
MT	24
EOF

GT_BASE=ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606/genotype
SNP_BASE=ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606/ASN1_flat

j=0
for i in `seq 1 22` X Y MT ; do
	IN_NAME=$i
	if [ "$i" == "MT" ] ; then OUT_NAME=M ; fi
	perl db2ssnp -asm=reference \
	             -cmap=.${NAME}snps/snp_cmap.txt \
	             -snps=$SNP_BASE/ds_flat_ch$i.flat.gz \
	             -freqs=$GT_BASE/gt_chr$IN_NAME.xml.gz \
	              > .${NAME}snps/chr$j.snps
	j=`expr $j + 1`
done
mv .${NAME}snps ${NAME}snps
echo "Output in ${NAME}snps"
