#!/bin/sh

#
# cb-terminate
#
# Authors: Ben Langmead and Michael C. Schatz
#    Date: 9/26/2009
#
# Guides the user through setting up a Crossbow run.
#

d=`dirname "$0"`
pushd "$d"/bin > /dev/null
sh cmd-hadoop-cluster proxy $*
popd > /dev/null
