#!/bin/sh

#
# cb-terminate
#
# Authors: Ben Langmead and Michael C. Schatz
#    Date: 9/26/2009
#
# Guides the user through setting up a Crossbow run.
#

[ -z "$1" ] && echo "Must specify cluster name as argument" && exit 1

d=`dirname "$0"`
pushd "$d"/bin > /dev/null
sh terminate-hadoop-cluster $*
popd > /dev/null
